title: Linux Fundamentals
email: linuxworkshop67@gmail.com
description: >-
        Here you will find all the information about CIS 106 Linux fundamentals.
baseurl: "" 
url: "" 
#For local development
#theme: just-the-docs

#For github deployment
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

collections:
  modules:
    permalink: "/:collection/:path/"
    output: true

  week_report:
    permalink: "/:collection:/:path"
    output: true

  labs:
    permalink: "/:collection/:path/"
    output: true

  docs:
    permalink: "/:collection/:path/"
    output: true

  guides:
    permalink: "/:collection/:path/"
    output: true

  project:
    permalink: "/:collection/:path/"
    output: true
  final_exam:
    permalink: "/:collection/:path/"
    output: true

  extra:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    modules:
      name: Modules
    week_report:
      name: Homework
    labs:
      name: Labs

    docs:
      name: Documentation    
    guides:
      name: Guides
    project:
      name: Project    
    extra:
      name: Extra  
    final_exam:
      name: Final_Exam
