set number
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set guicursor=
set nohlsearch
set hidden
set noerrorbells
set incsearch
set scrolloff=8
set signcolumn=yes
set colorcolumn=80
call plug#begin('/home/adrian/.vim/plugged')

Plug 'dominikduda/vim_current_word'
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'rust-lang/rust.vim'

call plug#end()
let g:vim_current_word#highlight_twins = 1
let g:vim_current_word#highlight_current_word = 1
hi CurrentWord ctermbg=53
hi CurrentWordTwins ctermbg=237
